### ISSUE TITLE
Exclude nonmonophyletic individuals from further analysis

### ISSUE THREAD

**Issue by hawkrives** [hybsearch/hybsearch#38]
If you have two dogs in a branch with five cats, the cats are the predominant species of that branch; thus, when we identify a dog as being nonmonophyletic, we should exclude that dog from future comparisons. 

---

I believe that this is what the global_nm array is supposed to do.

**Comment by OmarShehata** [comment]
Example test file is trio171sequence

**Comment by OmarShehata** [comment]
Is this complete? Did the biologists verify it? @mollysrour

**Comment by rye** [comment]
The first pass on this was pushed in #103, but the test file you mention, `trio171sequence`, does not work due to some ent problems.  @hawkrives said he'd take a look at it tomorrow, but provided that the input is formatted like what we have in `emydura.gb` or any of the other emydura examples, we should have this mostly if not completely done, and it _should_ work.

**Comment by rye** [comment]
(To be more concise: the mbnb pipeline, which will get deployed soonish, does have that pruning magic built out.)

**Comment by hawkrives** [comment]
I think we have this solved, but I'd like to keep it open until we can verify on the trio171 dataset.

**Comment by OmarShehata** [comment]
We're done with this right @hawkrives ? Can we close?

**Comment by hawkrives** [comment]
This is now fully solved, I believe.
