### ISSUE TITLE
Cache intermediate pipeline step results in the build pipeline

### ISSUE THREAD

**Issue by hawkrives** [hybsearch/hybsearch#74]
Should speed up the analysis process.

I think I'd like to tackle this by caching the result of each "step" in the pipeline within the docker container, so that if something does go wonky we can just restart the image to clear the caches.

- [ ] Rework the pipeline to be clearer about data sending / caching
- [ ] Automatically cache the output of each stage based on the (input?) content

**Comment by OmarShehata** [comment]
This would be super nice. This might be a stretch goal but it would be really nice if there was some directory where the cache was saved. I've been manually doing this during development because waiting 20 seconds vs 1 second matters a lot when you're iterating. For example I'd export the analyzed newick tree and the aligned sequences and then just run the pruning algorithm on those.

**Comment by hawkrives** [comment]
Ah, I wasn't thinking about local dev. 

Yeah, we might as well just mount a directory from the host then. 

I'll do that and add docs for how to invoke docker with the cache folder. Then it'll persist then across runs too, and you can clear it if you need to.
